name: Inventory Front End CI

on:
    push:
        branches:
          - master
    pull_request:
      branches:
          - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1 checkout the repository
      - name: checkout code
        uses: actions/checkout@v3

    # 2 Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

    # 3 Install dependencies
      - name: Install dependencies
        run: npm ci 

    # 4 Build Project
      - name: Build Project
        run: npm run build

    # 5 Deploy to Render
      - name: Deploy to Render
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Triggering deploy to Render..."
          curl -X POST "https://api.render.com/deploy/srv-${RENDER_SERVICE_ID}" \
          -H "Authorization: Bearer ${RENDER_API_KEY}" \
          -H "Accept: application/json"     



        